import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import PageTransition from "@/Components/PageTransition";
import StairTransition from "@/Components/StairTransition.jsx";

const jetBrains_Mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
        <title>Abubakar Dev</title>
      </head>
      <body className={jetBrains_Mono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}

// import { Poppins } from "next/font/google";
// import "./globals.css";
// import Header from "@/Components/Header";
// import PageTransition from "@/Components/PageTransition";
// import StairTransition from "@/Components/StairTransition.jsx";
// import Head from "next/head";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// export const metadata = {
  //   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
  //   return (
    //     <html lang="en">
    //       <Head>
    //         <link rel="icon" href="/favicon.png" type="image/png" />
    //         <title>Abubakar Dev</title>
//       </Head>;
//       <body className={poppins.variable}>
//         <Header />
//         <StairTransition />
//         <PageTransition>{children}</PageTransition>
//       </body>
//     </html>
//   );
// }

// import { Ubuntu } from "next/font/google";
// import "./globals.css";
// import Header from "@/Components/Header";
// import PageTransition from "@/Components/PageTransition";
// import StairTransition from "@/Components/StairTransition.jsx";
// import Head from "next/head";

// const ubuntu = Ubuntu({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "700"],
//   variable: "--font-ubuntu",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <Head>
//         <link rel="icon" href="/favicon.png" type="image/png" />
//         <title>Abubakar Dev</title>
//       </Head>;
//       <body className={ubuntu.variable}>
//         <Header />
//         <StairTransition />
//         <PageTransition>{children}</PageTransition>
//       </body>
//     </html>
//   );
// }
